export const countries = [
  { countryName: "India", currency: "INR" },
  { countryName: "Saudi Arabia", currency: "SAR" },
  { countryName: "United Arab Emirates", currency: "AED" },
  { countryName: "Iraq", currency: "IQD" },
  { countryName: "Iran", currency: "IRR" },
  { countryName: "Jordan", currency: "JOD" },
  { countryName: "Lebanon", currency: "LBP" },
  { countryName: "Syria", currency: "SYP" },
  { countryName: "Israel", currency: "ILS" },
  { countryName: "Palestine", currency: "ILS" },
  { countryName: "Kuwait", currency: "KWD" },
  { countryName: "Qatar", currency: "QAR" },
  { countryName: "Oman", currency: "OMR" },
  { countryName: "Bahrain", currency: "BHD" },
  { countryName: "Yemen", currency: "YER" },
];

export const currencies = [
  "INR",
  "SAR",
  "AED",
  "IQD",
  "IRR",
  "JOD",
  "LBP",
  "SYP",
  "ILS",
  "ILS",
  "KWD",
  "QAR",
  "OMR",
  "BHD",
  "YER",
];
export const currencyNames = [
  "Rupee",
  "Saudi Riyal",
  "Dirham",
  "Iraqi Dinar",
  "Iranian Rial",
  "Jordanian Dinar",
  "Lebanese Pound",
  "Syrian Pound",
  "Israeli Shekel",
  "Kuwaiti Dinar",
  "Qatari Riyal",
  "Omani Rial",
  "Bahraini Dinar",
  "Yemeni Rial",
];
