export const countries = [
  { countryName: "India", currency: "INR", currencyName: "Rupee", subunit: "Paisa", symbol: "₹" },
  { countryName: "Saudi Arabia", currency: "SAR", currencyName: "Riyal", subunit: "Halala", symbol: "ر.س" },
  { countryName: "United Arab Emirates", currency: "AED", currencyName: "Dirham", subunit: "Fils", symbol: "د.إ" },
  { countryName: "Iraq", currency: "IQD", currencyName: "Dinar", subunit: "Fils", symbol: "د.ع" },
  { countryName: "Iran", currency: "IRR", currencyName: "Rial", subunit: "Dinar", symbol: "﷼" },
  { countryName: "Jordan", currency: "JOD", currencyName: "Dinar", subunit: "Piastre", symbol: "د.أ" },
  { countryName: "Lebanon", currency: "LBP", currencyName: "Pound", subunit: "Piastre", symbol: "ل.ل" },
  { countryName: "Syria", currency: "SYP", currencyName: "Pound", subunit: "Piastre", symbol: "س.س" },
  { countryName: "Israel", currency: "ILS", currencyName: "Shekel", subunit: "Agorot", symbol: "₪" },
  { countryName: "Palestine", currency: "ILS", currencyName: "Shekel", subunit: "Agorot", symbol: "₪" },
  { countryName: "Kuwait", currency: "KWD", currencyName: "Dinar", subunit: "Fils", symbol: "د.ك" },
  { countryName: "Qatar", currency: "QAR", currencyName: "Riyal", subunit: "Dirham", symbol: "ر.ق" },
  { countryName: "Oman", currency: "OMR", currencyName: "Rial", subunit: "Baisa", symbol: "ر.ع" },
  { countryName: "Bahrain", currency: "BHD", currencyName: "Dinar", subunit: "Fils", symbol: ".د.ب" },
  { countryName: "Yemen", currency: "YER", currencyName: "Rial", subunit: "Baisa", symbol: "ر.ي" },
];


export const currencies = [
  "INR",
  "SAR",
  "AED",
  "IQD",
  "IRR",
  "JOD",
  "LBP",
  "SYP",
  "ILS",
  "ILS",
  "KWD",
  "QAR",
  "OMR",
  "BHD",
  "YER",
];
export const currencyNames = [
  "Rupee",
  "Saudi Riyal",
  "Dirham",
  "Iraqi Dinar",
  "Iranian Rial",
  "Jordanian Dinar",
  "Lebanese Pound",
  "Syrian Pound",
  "Israeli Shekel",
  "Kuwaiti Dinar",
  "Qatari Riyal",
  "Omani Rial",
  "Bahraini Dinar",
  "Yemeni Rial",
];
