export const defaultPrintSettings = {
  voucher: "voucher",
  printTitle: null,
  showCompanyDetails: true,
  showDiscount: true,
  showDiscountAmount: true,
  showHsn: true,
  showTaxPercentage: true,
  showInclTaxRate: false,
  showTaxAnalysis: false,
  showTeamsAndConditions: true,
  showBankDetails: true,
  showTaxAmount: true,
  showStockWiseTaxAmount: true,
  showRate: true,
  showQuantity: true,
  showStockWiseAmount: true,
  showNetAmount: true,
};
